### ISSUE TITLE
Connecting MacBook Pro 2010 to X-Carve

### ISSUE THREAD

**Issue by millerama** [sir-buckyball/chrome-gcode-sender#35]
I am getting an error when trying to connect: 
Chrome did not use requested serial connection option. [ctsFlowControl; expected:false, actual:true]

Any advice on how to set ctsFlowControl to false?

Thanks,
Rick (noob)

**Comment by sir-buckyball** [comment]
What version of chrome are you running? This is listed at chrome://chrome/

The bad news is that there is really not much that can be done in this case. The system is ignoring a parameter which may well be necessary for communication to be established properly. I know I have this issue on my 2006 mac mini, but have successfully controlled a shapeoko 2 (older version of an x-carve) from a 2009 macbook.

**Comment by kevjett** [comment]
Any fix? I'm having same issue?

Version 49.0.2623.87 (64-bit)

**Comment by sir-buckyball** [comment]
As I said before, there is really not much I can do. It appears that there are some combinations of computers, operating system, and chrome versions where the Serial API of chrome does not do what is requested.
