### ISSUE TITLE
Looking for a successful x-carve run under windows 8 

### ISSUE THREAD

**Issue by decarlowoodworks** [sir-buckyball/chrome-gcode-sender#36]
I have a x-carve by inventables and windows 8, I added gcode-sender to chrome. When I send the gcode, the first line, G20, is displayed in the console then I get a Alarm Lock and stops. I was able to get the Grbl version, 0.9j . I also toggled the connect/disconnect to see what would happen. It displayed $\x2=y .

Any help would be great!

**Comment by sir-buckyball** [comment]
G20 tells your x-carve that you'll be sending coordinates in inches (as opposed to millimeters). It's a safe command in that your machine should do nothing upon receiving it. This means that your machine was likely already in an alarm lock state when you sent the first command.

There are multiple issues which can cause an alarm lock state:
- alarm pin is triggered (check that your limit switches are functioning properly with a multimeter)
- soft limits triggered (happens when the machine thinks that the carriage is outside the safety area; unlikely if you just turned on the machine)


It is possible to disable the alarms lock, but I strongly urge you to find the reason for the fault. This page discusses the matter more: https://github.com/grbl/grbl/wiki/Configuring-Grbl-v0.9

**Comment by decarlowoodworks** [comment]
Thanks for the info. I did some more testing. I can't figure out why its failing on a G3, any ideas?

I exported Easel generated g-code and used the chrome gcode sender, it worked with out error. Then I used the Fusion 360 generated g-code. The only difference was the G3 command with I and J values and got an "error: Invalid gcode ID:33".

Here is the console:
error: Alarm lock
Grbl 0.9j ['$' for help]
['$H'|'$X' to unlock]  ok
$X
[Caution: Unlocked]  ok
G20  ok
G90  ok
G1 Z0.15000 F9.0  ok
M9  ok
G0 X-0.0531 Y-3.3017 Z0.7225\xd Z0.3225  okokok
G1 Z0.1619 F30.0 Z0.1325\xd X-0.0529 Y-3.3019 Z0.1297\xd X-0.0525 Y-3.3028 Z0.1271\xd X-0.0519 Y-3.3041 Z0.1247\xd X-0.0511 Y-3.3059 Z0.1227\xd X-0.0501 Y-3.3081 Z0.1212\xd X-0.049 Y-3.3105 Z0.1203\xd X-0.0478 Y-3.313 Z0.12\xd X-0.0426 Y-3.3244
  okokokok
G17  okokokokokokok
G3 X-0.0261 Y-3.3305 I-0.0313 J-3.3192
error: Invalid gcode ID:33
M112
\x18
error: Unsupported command
Grbl 0.9j ['$' for help]


The g-code following the G3:

  G1 X0.0794 Y-3.2821
  X0.1818 Y-3.2324
  X0.2817 Y-3.1812

From M112 on is when I hit the E-STOP .

**Comment by sir-buckyball** [comment]
From that console output, it looks as if your gcode file uses carriage-return characters (0x0D) instead of newline characters (0x0A).

As an experiment, would you mind switching which character you use to delineate the lines? I would guess that the line is being treated as a very long line, and is overrunning the buffer of your X-Carve, resulting in a truncated message.

If that experiment does the trick, we can update the file parsing routine (though I don't think 0x0D is an appropriate delineation character [it stems from a typewriter returning the carriage to the left]).

**Comment by decarlowoodworks** [comment]
I tried it but got the same result. I'm assuming the I and J commands are valid. I made a similar design using Easel then exported the g-code. I noticed it did not generate I and J's to carve the arcs. Any ideas I can try?

I used Fusion 360 to generate the g-code, currently they do not have a post process for Inventables X-Carve. Do you have any recommendations?

**Comment by sir-buckyball** [comment]
I don't suppose you'd mind sharing your problematic gcode file so I can play with it on my setup?

I have not used Fusion360. What output processors are available? I'd recommend picking the most generic sounding output.

FYI: I and J are vector coordinates to define the arc interpolation centerpoint (G3). Some programs just treat curves as a series of small lines which is why you may not see the G3 command in your Easel output.

**Comment by decarlowoodworks** [comment]
I modified one of the post processors to generate R instead of IJK and was able to get it to run correctly. But I think IJK should work with X-Carve. Here's the gcode (w/IJK), maybe you can figure out why its not running. Thanks for the help!

G20
G90
G1 Z0.15000 F9.0
M3 S14000
G0 X-0.0531 Y-3.3017 Z0.7225 F9.0 
Z0.3225
G1 Z0.1619 F30.0Z0.1325
X-0.0529 Y-3.3019 Z0.1297
X-0.0525 Y-3.3028 Z0.1271
X-0.0519 Y-3.3041 Z0.1247
X-0.0511 Y-3.3059 Z0.1227
X-0.0501 Y-3.3081 Z0.1212
X-0.049 Y-3.3105 Z0.1203
X-0.0478 Y-3.313 Z0.12
X-0.0426 Y-3.3244
G17 
G3 X-0.0261 Y-3.3305 I-0.0313 J-3.3192G1 
X0.0794 Y-3.2821
X0.1818 Y-3.2324
X0.2817 Y-3.1812
X0.379 Y-3.1283
X0.4738 Y-3.0738
X0.566 Y-3.0178
X0.6557 Y-2.96
X0.6993 Y-2.9306
X0.7423 Y-2.9007
X0.7848 Y-2.8704
X0.8265 Y-2.8397
X0.8675 Y-2.8086
X0.9078 Y-2.777
X0.9474 Y-2.745
X0.9864 Y-2.7125
X1.0245 Y-2.6796
X1.062 Y-2.6463
X1.0987 Y-2.6125
X1.1347 Y-2.5782
X1.1699 Y-2.5435
X1.2044 Y-2.5084
X1.2382 Y-2.4727
X1.2711 Y-2.4366
X1.3033 Y-2.4
X1.3348 Y-2.3629
X1.3654 Y-2.3254
X1.3953 Y-2.2873
X1.4244 Y-2.2488
X1.4527 Y-2.2097
X1.4802 Y-2.1702
X1.507 Y-2.1301
X1.5329 Y-2.0896
X1.5581 Y-2.0485
X1.5825 Y-2.0069
X1.6061 Y-1.9647
X1.6289 Y-1.9221
X1.651 Y-1.879
X1.6722 Y-1.8353
X1.6927 Y-1.7911
X1.7125 Y-1.7464
X1.7315 Y-1.7011
X1.7497 Y-1.6554
X1.7672 Y-1.6091
X1.7839 Y-1.5623
X1.8 Y-1.5151
X1.8152 Y-1.4673
X1.8298 Y-1.419
X1.8437 Y-1.3702
X1.8568 Y-1.321
X1.8692 Y-1.2712
X1.881 Y-1.221
X1.892 Y-1.1703
X1.9024 Y-1.1191
X1.9121 Y-1.0674
X1.9212 Y-1.0153
X1.9295 Y-0.9627
X1.9372 Y-0.9099
X1.9507 Y-0.8023
X1.9616 Y-0.6931
X1.97 Y-0.5822
X1.9759 Y-0.4696
X1.9794 Y-0.3554
X1.9804 Y-0.2394
X1.979 Y-0.1218
X1.9751 Y-0.002
G2 X2.0376 Y0.0625 I2.0376 J0.0
G1 X3.0672
G2 X3.1297 Y-0.0021 I3.0672 J0.0
G1 X3.1257 Y-0.1194
X3.1241 Y-0.2346
X3.1247 Y-0.3482
X3.1277 Y-0.4602
X3.133 Y-0.5707
X3.1407 Y-0.6796
X3.1507 Y-0.7868
X3.1632 Y-0.8923
X3.1782 Y-0.9961
X3.1957 Y-1.0984
X3.2054 Y-1.1486
X3.2158 Y-1.1985
X3.2268 Y-1.248
X3.2384 Y-1.2971
X3.2508 Y-1.3456
X3.2638 Y-1.3937
X3.2775 Y-1.4413
X3.2919 Y-1.4885
X3.3069 Y-1.5352
X3.3227 Y-1.5814
X3.3392 Y-1.6271
X3.3563 Y-1.6723
X3.3742 Y-1.7171
X3.3929 Y-1.7613
X3.4122 Y-1.8051
X3.4323 Y-1.8483
X3.4531 Y-1.8911
X3.4746 Y-1.9333
X3.4969 Y-1.9751
X3.52 Y-2.0164
X3.5438 Y-2.0572
X3.5683 Y-2.0975
X3.5936 Y-2.1373
X3.6196 Y-2.1766
X3.6464 Y-2.2155
X3.6739 Y-2.2538
X3.7022 Y-2.2917
X3.7312 Y-2.3292
X3.761 Y-2.3661
X3.7915 Y-2.4027
X3.8227 Y-2.4387
X3.8546 Y-2.4743
X3.8873 Y-2.5095
X3.9207 Y-2.5442
X3.9548 Y-2.5784
X3.9896 Y-2.6123
X4.0251 Y-2.6457
X4.0613 Y-2.6787
X4.0982 Y-2.7112
X4.1358 Y-2.7434
X4.174 Y-2.7751
X4.2127 Y-2.8063
X4.2927 Y-2.8679
X4.3751 Y-2.9277
X4.4601 Y-2.986
X4.5476 Y-3.0427
X4.6375 Y-3.0978
X4.73 Y-3.1515
X4.8248 Y-3.2037
X4.9221 Y-3.2543
X4.9942 Y-3.2899
X5.0574 Y-3.2577
X5.146 Y-3.2099
X5.2327 Y-3.1604
X5.3174 Y-3.1093
X5.4002 Y-3.0565
X5.4809 Y-3.002
X5.5597 Y-2.9457
X5.6365 Y-2.8877
X5.7112 Y-2.828
X5.7837 Y-2.7664
X5.8541 Y-2.703
X5.9224 Y-2.6377
X5.9885 Y-2.5704
X6.0523 Y-2.5013
X6.114 Y-2.4299
X6.1437 Y-2.3937
X6.1731 Y-2.3569
X6.2018 Y-2.3195
X6.23 Y-2.2816
X6.2576 Y-2.2432
X6.2846 Y-2.2043
X6.311 Y-2.1648
X6.3368 Y-2.1248
X6.3621 Y-2.0843
X6.3867 Y-2.0432
X6.4108 Y-2.0015
X6.4344 Y-1.9594
X6.4573 Y-1.9168
X6.4795 Y-1.8737
X6.5227 Y-1.7855
X6.5634 Y-1.6953
X6.602 Y-1.6031
X6.6385 Y-1.5088
X6.6727 Y-1.4126
X6.7049 Y-1.3143
X6.7351 Y-1.2141
X6.7633 Y-1.112
X6.7895 Y-1.0081
X6.8137 Y-0.9024
X6.8362 Y-0.7949
X6.8567 Y-0.6856
X6.8754 Y-0.5747
X6.8924 Y-0.4621
X6.9075 Y-0.3478
X6.9209 Y-0.2319
X6.9325 Y-0.1144
X6.9424 Y0.0052
G2 X7.0047 Y0.0625 I7.0047 J0
G1 X8.0235
G2 X8.086 Y0.0021 I8.0235 J0
G1 X8.09 Y-0.1143
X8.096 Y-0.2287
X8.104 Y-0.3416
X8.114 Y-0.4529
X8.1261 Y-0.5627
X8.1403 Y-0.671
X8.1566 Y-0.7776
X8.175 Y-0.8826
X8.1956 Y-0.986
X8.2184 Y-1.0877
X8.2435 Y-1.1876
X8.271 Y-1.2858
X8.3007 Y-1.3823
X8.3328 Y-1.4768
X8.3676 Y-1.5698
X8.3857 Y-1.6152
X8.4045 Y-1.6604
X8.424 Y-1.7051
X8.4442 Y-1.7493
X8.4649 Y-1.793
X8.4864 Y-1.8363
X8.5084 Y-1.879
X8.5312 Y-1.9213
X8.5546 Y-1.9631
X8.5786 Y-2.0044
X8.6033 Y-2.0452
X8.6287 Y-2.0856
X8.6547 Y-2.1254
X8.6814 Y-2.1648
X8.7088 Y-2.2037
X8.7368 Y-2.2421
X8.7655 Y-2.2801
X8.7948 Y-2.3176
X8.8248 Y-2.3546
X8.8555 Y-2.3912
X8.8868 Y-2.4274
X8.9186 Y-2.4628
X8.9846 Y-2.533
X9.0529 Y-2.6013
X9.1238 Y-2.6679
X9.197 Y-2.7328
X9.2727 Y-2.7961
X9.3507 Y-2.8577
X9.431 Y-2.9178
X9.5136 Y-2.9763
X9.5985 Y-3.0333
X9.6856 Y-3.0888
X9.7748 Y-3.1427
X9.8662 Y-3.1952
X9.9597 Y-3.2462
X10.0277 Y-3.2813
X10.0977 Y-3.2463
X10.1933 Y-3.1958
X10.2866 Y-3.1437
X10.3775 Y-3.0902
X10.4661 Y-3.0352
X10.5523 Y-2.9786
X10.636 Y-2.9205
X10.7173 Y-2.8608
X10.796 Y-2.7995
X10.8724 Y-2.7364
X10.9094 Y-2.7045
X10.9458 Y-2.672
X10.9816 Y-2.6391
X11.0168 Y-2.6057
X11.0512 Y-2.572
X11.085 Y-2.5377
X11.1181 Y-2.5031
X11.1505 Y-2.468
X11.1823 Y-2.4325
X11.2132 Y-2.3965
X11.2436 Y-2.36
X11.2731 Y-2.3231
X11.3021 Y-2.2858
X11.3302 Y-2.2479
X11.3577 Y-2.2096
X11.3844 Y-2.1708
X11.4104 Y-2.1316
X11.4357 Y-2.0918
X11.4603 Y-2.0516
X11.4841 Y-2.0108
X11.5073 Y-1.9696
X11.5297 Y-1.9279
X11.5514 Y-1.8857
X11.5724 Y-1.843
X11.5926 Y-1.7998
X11.6122 Y-1.7562
X11.6311 Y-1.7119
X11.6493 Y-1.6673
X11.6668 Y-1.6221
X11.6836 Y-1.5765
X11.6997 Y-1.5304
X11.7152 Y-1.4838
X11.73 Y-1.4367
X11.7441 Y-1.3892
X11.7576 Y-1.3412
X11.7704 Y-1.2929
X11.7942 Y-1.1944
X11.8154 Y-1.0943
X11.8342 Y-0.9924
X11.8505 Y-0.8888
X11.8645 Y-0.7835
X11.8762 Y-0.6766
X11.8855 Y-0.568
X11.8926 Y-0.4578
X11.8974 Y-0.3461
X11.9 Y-0.2328
X11.9004 Y-0.1179
X11.8986 Y-0.001
G2 X11.9611 Y0.0625 I11.9611 J0
G1 X13.0625
G2 X13.1249 Y-0.0036 I13.0625 J0
G1 X13.1181 Y-0.1208
X13.1138 Y-0.2358
X13.112 Y-0.3492
X13.1127 Y-0.461
X13.116 Y-0.5711
X13.1218 Y-0.6796
X13.1303 Y-0.7866
X13.1354 Y-0.8392
X13.1413 Y-0.8915
X13.1479 Y-0.9434
X13.1551 Y-0.9949
X13.163 Y-1.0459
X13.1716 Y-1.0965
X13.1809 Y-1.1466
X13.1909 Y-1.1962
X13.2016 Y-1.2454
X13.213 Y-1.2941
X13.2251 Y-1.3423
X13.238 Y-1.3901
X13.2516 Y-1.4374
X13.266 Y-1.4842
X13.2811 Y-1.5305
X13.2969 Y-1.5764
X13.3135 Y-1.6217
X13.3309 Y-1.6666
X13.3491 Y-1.7109
X13.368 Y-1.7547
X13.3877 Y-1.7981
X13.4083 Y-1.8409
X13.4296 Y-1.8833
X13.4517 Y-1.9251
X13.4746 Y-1.9665
X13.4983 Y-2.0073
X13.5228 Y-2.0477
X13.5482 Y-2.0876
X13.5743 Y-2.127
X13.6013 Y-2.1659
X13.629 Y-2.2043
X13.6576 Y-2.2422
X13.6869 Y-2.2797
X13.7171 Y-2.3167
X13.748 Y-2.3532
X13.7798 Y-2.3893
X13.8123 Y-2.4249
X13.8456 Y-2.46
X13.8797 Y-2.4947
X13.9145 Y-2.529
X13.9502 Y-2.5628
X13.9866 Y-2.5962
X14.0237 Y-2.6292
X14.0615 Y-2.6617
X14.1001 Y-2.6939
X14.1395 Y-2.7256
X14.1796 Y-2.7569
X14.2204 Y-2.7877
X14.2618 Y-2.8182
X14.304 Y-2.8483
X14.3469 Y-2.8779
X14.3903 Y-2.9071
X14.4797 Y-2.9645
X14.5716 Y-3.0203
X14.6662 Y-3.0746
X14.7634 Y-3.1273
X14.8632 Y-3.1785
X14.9656 Y-3.2283
X15.0433 Y-3.2639
X15.1194 Y-3.2242
X15.2198 Y-3.1693
X15.3178 Y-3.1131
X15.4133 Y-3.0557
X15.5063 Y-2.997
X15.5969 Y-2.937
X15.685 Y-2.8757
X15.7704 Y-2.8131
X15.8532 Y-2.7492
X15.9334 Y-2.6839
X16.011 Y-2.617
X16.0485 Y-2.5833
X16.0855 Y-2.549
X16.1218 Y-2.5144
X16.1573 Y-2.4795
X16.1921 Y-2.4442
X16.2262 Y-2.4085
X16.2596 Y-2.3724
X16.2922 Y-2.3359
X16.3241 Y-2.2991
X16.3552 Y-2.2619
X16.3856 Y-2.2243
X16.4152 Y-2.1863
X16.4441 Y-2.1479
X16.4721 Y-2.1091
X16.4995 Y-2.0699
X16.526 Y-2.0303
X16.5517 Y-1.9903
X16.5767 Y-1.9498
X16.601 Y-1.9089
X16.6244 Y-1.8677
X16.6471 Y-1.826
X16.669 Y-1.7839
X16.6902 Y-1.7414
X16.7106 Y-1.6984
X16.7302 Y-1.6551
X16.7491 Y-1.6113
X16.7672 Y-1.567
X16.7846 Y-1.5224
X16.8013 Y-1.4774
X16.8173 Y-1.4319
X16.8325 Y-1.386
X16.847 Y-1.3397
X16.8608 Y-1.2931
X16.8739 Y-1.2459
X16.8863 Y-1.1984
X16.898 Y-1.1505
X16.9091 Y-1.1022
X16.9194 Y-1.0538
X16.9382 Y-0.955
X16.9542 Y-0.855
X16.9677 Y-0.7534
X16.9787 Y-0.6504
X16.9871 Y-0.546
X16.9931 Y-0.4401
X16.9966 Y-0.3328
X16.9977 Y-0.2241
X16.9964 Y-0.1141
X16.9927 Y-0.0021
G2 X17.0551 Y0.0625 I17.0551 J0
G1 X18.0739
G2 X18.1363 Y-0.0029 I18.0739 J0
G1 X18.1311 Y-0.1146
X18.1283 Y-0.2243
X18.128 Y-0.3327
X18.13 Y-0.4397
X18.1345 Y-0.5453
X18.1415 Y-0.6495
X18.151 Y-0.7523
X18.1631 Y-0.8537
X18.1777 Y-0.9536
X18.195 Y-1.0523
X18.2046 Y-1.1007
X18.215 Y-1.1489
X18.226 Y-1.1968
X18.2377 Y-1.2443
X18.25 Y-1.2913
X18.2631 Y-1.338
X18.2769 Y-1.3843
X18.2915 Y-1.4301
X18.3067 Y-1.4756
X18.3227 Y-1.5207
X18.3394 Y-1.5653
X18.3568 Y-1.6096
X18.375 Y-1.6534
X18.394 Y-1.6968
X18.4137 Y-1.7398
X18.4342 Y-1.7823
X18.4554 Y-1.8245
X18.4773 Y-1.8663
X18.5001 Y-1.9076
X18.5237 Y-1.9485
X18.548 Y-1.9891
X18.573 Y-2.0292
X18.5989 Y-2.0689
X18.6255 Y-2.1082
X18.6529 Y-2.1471
X18.6811 Y-2.1856
X18.7101 Y-2.2238
X18.7397 Y-2.2615
X18.7702 Y-2.2988
X18.8014 Y-2.3358
X18.8334 Y-2.3724
X18.8661 Y-2.4087
X18.8995 Y-2.4445
X18.9337 Y-2.48
X18.9685 Y-2.5152
X19.0042 Y-2.55
X19.0405 Y-2.5844
X19.0773 Y-2.6183
X19.1536 Y-2.6856
X19.2325 Y-2.7514
X19.314 Y-2.8158
X19.3982 Y-2.8789
X19.485 Y-2.9407
X19.5743 Y-3.0013
X19.6662 Y-3.0606
X19.7496 Y-3.1121
X19.835 Y-3.1626
X19.9223 Y-3.2121
X19.9979 Y-3.2533
X20.0508 Y-3.2531
X20.1155 Y-3.2117
X20.1936 Y-3.16
X20.2701 Y-3.1073
X20.3452 Y-3.0537
X20.4278 Y-2.9924
X20.5083 Y-2.9299
X20.587 Y-2.8662
X20.6636 Y-2.8013
X20.7382 Y-2.7352
X20.8107 Y-2.6678
X20.8811 Y-2.5992
X20.9493 Y-2.5293
X21.0153 Y-2.4581
X21.0791 Y-2.3855
X21.1406 Y-2.3115
X21.1998 Y-2.2362
X21.2567 Y-2.1594
X21.3112 Y-2.0811
X21.3634 Y-2.0014
X21.4131 Y-1.9202
X21.4605 Y-1.8375
X21.5055 Y-1.7533
X21.5481 Y-1.6675
X21.5885 Y-1.5802
X21.6266 Y-1.4915
X21.6623 Y-1.4012
X21.696 Y-1.3095
X21.7274 Y-1.2164
X21.7567 Y-1.1219
X21.7839 Y-1.0259
X21.8091 Y-0.9286
X21.8323 Y-0.83
X21.8535 Y-0.7301
X21.8727 Y-0.6289
X21.8901 Y-0.5264
X21.9056 Y-0.4227
X21.9192 Y-0.3178
X21.931 Y-0.2117
X21.9409 Y-0.1044
X21.9491 Y0.0047
G2 X22.0115 Y0.0625 I22.0115 J0
G1 X23.0027
G2 X23.0652 Y0.0024 I23.0027 J0
G1 X23.0696 Y-0.1112
X23.0761 Y-0.2228
X23.0849 Y-0.3329
X23.0959 Y-0.4415
X23.1092 Y-0.5486
X23.1247 Y-0.6542
X23.1425 Y-0.7582
X23.1627 Y-0.8607
X23.1852 Y-0.9615
X23.2102 Y-1.0608
X23.2376 Y-1.1583
X23.2676 Y-1.2544
X23.2835 Y-1.3015
X23.3 Y-1.3484
X23.3172 Y-1.3948
X23.3351 Y-1.4407
X23.3537 Y-1.4863
X23.3729 Y-1.5313
X23.3928 Y-1.576
X23.4133 Y-1.6202
X23.4346 Y-1.6639
X23.4566 Y-1.7071
X23.4792 Y-1.7499
X23.5025 Y-1.7923
X23.5266 Y-1.8342
X23.5513 Y-1.8756
X23.5768 Y-1.9166
X23.603 Y-1.9571
X23.6299 Y-1.9971
X23.6575 Y-2.0368
X23.6858 Y-2.0759
X23.7148 Y-2.1146
X23.7446 Y-2.1529
X23.775 Y-2.1907
X23.8062 Y-2.2281
X23.8381 Y-2.265
X23.8707 Y-2.3016
X23.904 Y-2.3377
X23.9379 Y-2.3734
X23.9726 Y-2.4086
X24.0079 Y-2.4435
X24.0438 Y-2.4777
X24.1179 Y-2.5456
X24.1946 Y-2.6116
X24.2739 Y-2.6761
X24.3556 Y-2.7391
X24.4399 Y-2.8006
X24.5267 Y-2.8606
X24.6158 Y-2.9192
X24.7073 Y-2.9763
X24.8011 Y-3.032
X24.8972 Y-3.0863
X24.9955 Y-3.1392
X25.0962 Y-3.1907
X25.1996 Y-3.2411
G3 X25.2163 Y-3.2353 I25.2051 J-3.2299
G1 X25.2218 Y-3.2241
X25.223 Y-3.2216 Z0.1203
X25.2241 Y-3.2192 Z0.1212
X25.2252 Y-3.2171 Z0.1227
X25.2261 Y-3.2153 Z0.1247
X25.2267 Y-3.214 Z0.1271
X25.2271 Y-3.2132 Z0.1297
X25.2273 Y-3.2129 Z0.1325
G0 Z0.7225M5G0 X0.00000 Y0.00000

**Comment by sir-buckyball** [comment]
I've pushed a new release (2015.9.7.0). Please let me know if that does the trick for you.

This version adds support for the carriage return character being used as you have described it. This bug finally got me to add some tests to assert the expectations of the parsing code.
