### ISSUE TITLE
Can't seem to talk to stecraft 2

### ISSUE THREAD

**Issue by marcboivin** [sir-buckyball/chrome-gcode-sender#41]
First of all, thank you for such a great idea. I wanted to develop a web interface for my CnC and this is the perfect starting point.

I seem to run into an issue, though. My CnC uses a UC100 controller to interface USB to LPT1 port. On Windows and OSX gcode-sender doesn't see said port. 

Does it need ti be a TTY device for gcode-sender to work?

TIA,

**Comment by sir-buckyball** [comment]
Yes. This application does require a tty device. Under the hood it makes use of the chrome.serial API (https://developer.chrome.com/apps/serial) for communications with CNC machines.

If your machine requires something other than a serial connection, you are out of luck in terms of an out-of-the-box solution. Chrome does provide a more advanced USB API which would allow you to communicate with practically anything you plug into your USB port. You may have some luck with that.

https://developer.chrome.com/apps/usb
