### ISSUE TITLE
Chrome gcode sender port not showing

### ISSUE THREAD

**Issue by Ashenboy** [sir-buckyball/chrome-gcode-sender#54]
In my windows 7 lap, Chrome gcode sender app port list not showing? 
![CHROME](https://user-images.githubusercontent.com/66189779/83342617-1cb9d880-a30f-11ea-8931-de9ee12d078a.png)

**Comment by sir-buckyball** [comment]
Any useful debugging information would be in the javascript console. From this picture alone I cannot provide assistance.

That said, Chrome is  [dropping support](https://blog.chromium.org/2020/01/moving-forward-from-chrome-apps.html) for chrome applications in a few months and I expect this app will fade out of existence at that point. The replacement API's required have not yet been made generally available, and I do not expect to have the time/energy to port this application over.

As you appear to be using Windows, there should be a wide selection of alternative applications for you to use.
